version: '3'

services:
  app_alumnado:
    build: alumnado
    ports:
      - "8080:8080"
    environment:
      DB_URL: ${MYSQL_URL}
      DB_USERNAME: ${MYSQLUSER}
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    restart: always
    depends_on:
      alumnado:
        condition: service_healthy
  alumnado:
    image: mysql:8.0.33
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 10s
      retries: 10
